apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins_pipeline_kubernetes
  annotations:
    github.com/project-slug: anupkulkarni24/jenkins_pipeline_kubernetes
    backstage.io/kubernetes-id: hello-minikube
spec:
  type: service
  lifecycle: production
  owner: guest
